### ISSUE TITLE
Any plans to support mutations?

### ISSUE THREAD

**Issue by achton** [fnash/graphql-qb#1]

**Comment by fnash** [comment]
Hi,
Interesting, I will add it to the todo list.
I don't use mutations for the moment. I have to look at the syntax and come back to you.
Please feel free to make PR.

**Comment by achton** [comment]
@fnash The only other PHP library which has this support is https://github.com/RuslanHimikEvchev/graphql-query-builder

Unfortunately, it has no tests, and no support for fragments :-(

**Comment by fnash** [comment]
Yeah I tested that library. I does not deal with subqueries as objects. You must add array, not Query objects.
It has for the moment limited features, despite the many classes.

That is why I created my own.

@achton  What is the difference between a query and a mutation? Is it only the keywork "mutation" instead of the keyword "query" ?

**Comment by achton** [comment]
@fnash Mutations allow you to create and update data via the GQL endpoint, where queries only allow you to read. A mutation can also return data after the mutation is completed, same as queries.
The data to insert is also [passed as variables](https://medium.com/graphql-mastery/graphql-quick-tip-how-to-pass-variables-into-a-mutation-in-graphiql-23ecff4add57) (either inline or in a separate JSON transport).

That other repo does mutations *really* simply: https://github.com/RuslanHimikEvchev/graphql-query-builder/blob/master/src/Mutation/MutationBuilder.php

More on mutations:
https://graphql.org/learn/queries/#mutations

**Comment by fnash** [comment]
Yes thank you, but my question was about the syntax difference. I will add mutations this week.

**Comment by fnash** [comment]
@achton [v1.1](https://github.com/fnash/graphql-qb/releases/tag/v1.1) is out!

**Comment by achton** [comment]
@fnash Wow, well done :) I will test it today and get back to you with feedback. :+1:

**Comment by achton** [comment]
@fnash It seems the package is not yet updated on Packagist.org. Maybe you would like to [setup a Github hook](https://packagist.org/about#how-to-update-packages) so that future releases are automatically pushed to Packagist, otherwise it may take up to a week to show up there. You can also do a manual push there to make it scan you repo immediately.

**Comment by fnash** [comment]
v1.1 available

**Comment by achton** [comment]
I've tested 1.1 and unfortunately I am having some issues. Let me try and summarize, then we can split into separate issues if you'd like:

1. **Terminology:** I think there is a bit of confusion with the terminology. In GraphQL, **variables** seem to be those ["dynamic values" that are passed along separately to the server](https://graphql.org/learn/queries/#variables) in a query/mutation. In your library, however, the `variables()` method is used to configure something entirely different, ie. [**variable definitions**](https://graphql.org/learn/queries/#variable-definitions) (which is very confusing terms in the first place).
So the terms (in my understanding) are:
```gql
# First operation name & variable definitions
query HeroNameAndFriends($episode: Episode) {
  # Then query name and arguments
  hero(episode: $episode) {
    # Then fields
    name
    friends {
      name
    }
  }
}
```
Then separately, and in JSON format, come the **variables**:
```json
{
  "episode": "JEDI"
}
```
The above is true for both queries and mutations, but to translate the above to an example mutation that I have been testing with, I would like to do the following:
```php
  $mutation = Mutation::create('createContact')
    ->operationName('CreateTestContact')
    ->definitions([
      '$userdata' => 'Contact!',
    ])
    ->arguments([
      'input' => '$userdata'
    ])
    ->fields([
      'id',
      'errors' => [
        'type',
        'message',
      ]
    ])
    ->variables([
      'userdata' => [
        'firstName' => 'Thomas',
        'lastName' => 'Hansen',
        'phoneNumber' => '12345678',
        'email' => 'hello@example.com',
        'message' => 'Test with "quotes" and \'single quotes\' and áéóæøå and \\backslash.',
      ]
    ]);

```

2. **Separate variables transport**
If the above was possible, I would then expect to be able to fetch the query/mutation object and the variables array separately, so that I can pass them to my GQL client independently (I currently use [this one](https://github.com/softonic/graphql-client)). When sending the mutation via [Insomnia](https://insomnia.rest/) the raw JSON body sent via HTTP POST looks like this (linebreaks filtered out for readability):
```json
{
   "query":"mutation CreateTestContact($userdata: Contact!) {  createContact(input: $userdata)  {  id  errors { id type message path } }  } ",
   "variables":{
      "userdata":{
         "firstName":"Thomas",
         "lastName":"Hansen",
         "phoneNumber":"12345678",
         "email":"hello@example.com",
         "message":"Test with \"quotes\" and 'single quotes' and áéóæøå and \\backslash."
      }
   },
   "operationName":"CreateTestContact"
}
```
Notice how the query string and the JSON-encoded variables are kept separate.

3. **Multi-dimensional variable arrays**
Notice in my example mutation above, how variables contain one key, which refers to an array of variables. This represents the `Contact` input type in the GQL endpoint that I am interfacing with. I think it is common to use complex input types for variable definitions, and thus the library should support this scenario properly. It seems to only take booleans, floats and strings into account currently.

4. **Escape variable values**
Since GraphQL variables are dynamic and can contain user input (like a message from a form), it needs to be properly escaped. The most obvious way is to simply `json_encode()` it (like I have above). This should ensure that the transport layer doesn't choke on the string. Currently, my test message above fails in your library, because it contains quotes which are not escaped.

5. Use a **common interface** for `Query` and `Mutation`. This is helpful when using your library because my GQL connector is agnostic to the whether it's one or the other type of input. But I cannot typehint my methods if there is no common interface for the two, because PHP does not allow type hinting with multiple types.


Overall, I like the simplicity of your library, but I feel that the above changes are necessary for it to adhere to the GraphQL conventions, and to make the developer experience better. 
I'm very limited in the time I have to help implement the above, but can definitely test if you decide to make these changes. 

Let me know if you'd like me to create separate issues for the above.

**Comment by fnash** [comment]
@achton I understand what you want to do, but this library is just a query builder. Its unique goal is to generate a string at the end, representing the graphql quey. It is not a holder of variables.

So starting from that, the method name "Query::variables()" is clearly more intuitive than "Query::definitions()". definitions okay but definitions of what?

It is up to the developer to deal with the variables and escaping them, for the moment.

You can always create new issues for these 2 propositions (handle variables, common interface)

Can I close this mutations issue?

**Comment by achton** [comment]
@fnash I think I understand how you would like to limit scope of your library, which makes sense. Maybe I am looking at these issues the wrong way. I'll open separate issues for some of these changes and narrow down the discussion for each issue.

Thanks.
